Implement Po mode
Checkmk/checkmk-weblate-syncer pull request #4
Opened 2024-05-06 21:29 UTC by racicLuka

Implement Po mode

CMK-17270

2024-05-07 07:23 UTC, jherbel requested changes

2024-05-07 07:23 UTC, jherbel commented on checkmk_weblate_syncer/config.py
> +    checkmk_locale_po_file_path_pairs: list[
Sequence

2024-05-07 07:23 UTC, jherbel commented on checkmk_weblate_syncer/config.py
> +        tuple[
See my comment in the ticket. Let's use
```
class PoFilePair(BaseModel, frozen=True):
    checkmk: Annotated[Path, AfterValidator(_validate_path_is_relative)]
    locale: Annotated[Path, AfterValidator(_validate_path_is_relative)]
```
instead of a tuple. This avoids any doubts regarding the order of the paths in the tuple.

2024-05-07 07:23 UTC, jherbel commented on checkmk_weblate_syncer/po.py
> +            raise e
Let's continue in this case as well and store the error message for later

2024-05-07 07:23 UTC, jherbel commented on checkmk_weblate_syncer/po.py
> +        LOGGER.info("Checking formatting errors in %s", locale_po_file_path)
Let's move the code inside the loop into a separate function. This function should return something like this:
```
@dataclass(frozen=True)
class _Success:
    path: Path

@dataclass(frozen=True)
class _Failure:
    error_message: str

def _process_po_file_pair(...) -> _Sucess | _Failure:
    ...
```

2024-05-07 07:23 UTC, jherbel commented on checkmk_weblate_syncer/utils.py
> +from git import Repo
Let's avoid a separate utils.py. This can go into git.py. `repository_in_clean_state` can become private and we can simply call this function `repository_in_clean_state`.

2024-05-07 07:23 UTC, jherbel commented on checkmk_weblate_syncer/po.py
> +def _check_if_repo_is_dirty(repo: Repo) -> bool:
We can move this to git.py and reuse it in pot.py

2024-05-07 07:23 UTC, jherbel commented on checkmk_weblate_syncer/po.py
> +            raise e
continue

2024-05-07 07:23 UTC, jherbel commented on checkmk_weblate_syncer/po.py
> +            raise e
continue

2024-05-07 07:23 UTC, jherbel commented on checkmk_weblate_syncer/po.py
> +            raise e
continue

2024-05-07 07:23 UTC, jherbel commented on checkmk_weblate_syncer/po.py
> +def _commit_and_push_po_files(
We can move this to git.py and reuse it in pot.py

2024-05-07 07:23 UTC, jherbel commented on checkmk_weblate_syncer/po.py
> +    files_to_push_to_repo: list[Path],
Sequence

2024-05-10 07:06 UTC, racicLuka commented
At least now all of the checks pass, which wasn't the case before.
If this is OK with you, I will squash all the commits before merging them.

2024-05-10 09:24 UTC, jherbel approved these changes

2024-05-10 09:27 UTC, merged